name: 'Build Test'
on: [pull_request, push]

jobs:
  build:
    name: 'Check Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn
      - run: |
          yarn ci