name: 'Test Action'
on: [project_column]

jobs:
  test:
    name: 'Run Action'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          token: ${{ secrets.SOME_TOKEN }}