name: 'Test Action'
on: [push]

jobs:
  test:
    name: 'Run Action'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./
        with:
          client_id: ${{ secrets.DATE_LABEL_CLIENT_ID }}
          client_secret: ${{ secrets.DATE_LABEL_CLIENT_SECRET }}
          project_id: 1
          field_name: 'SomeField'